[package]
name = "test-bevy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_reflect = "0.5.0"
bevy_asset_ron = "0.2.0"
serde = "1.0.130"